---
title: "Relatório"
author: "Bernardo"
date: "07/11/2021"
output: html_document
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(plyr)
library(cowplot)
base_completa <- read.csv('Dados/base_completa.csv')
```

# Resultados

```{r echo=FALSE, message=FALSE, warning=FALSE}
graph <- base_completa %>% select(Resultado.Pool,Idade,Sexo) %>% 
  mutate(Resultado.Pool = as.factor(ifelse(Resultado.Pool != 'Não Detectável' |
                                   is.na(Resultado.Pool),
                                 'Indeterminado/Positivo','Não Detectável')),
         Idade = as.integer(Idade)) %>% 
  filter(!(is.na(Idade)),!(is.na(Resultado.Pool)),!(is.na(Sexo)))

legenda_masc <- ggplot(data=graph,aes(x=Idade)) + 
  geom_histogram(data=subset(graph,Sexo=="M"),
                 binwidth = 2,
                 aes(y=..count.., fill = 'Total'))+
  geom_histogram(data=subset(graph,Sexo=="M" & Resultado.Pool == "Não Detectável"),
               binwidth = 2,
               aes(y=..count.., fill = 'Não Detectáveis'))+
  scale_fill_manual(values = c('Total' = '#8cbfff','Não Detectáveis' = '#466cff'))+
  labs(fill = 'Sexo Masculino:')+
  theme(legend.position = "top")

legenda_fem <- ggplot(data=graph,aes(x=Idade)) + 
  geom_histogram(data=subset(graph,Sexo=="F"),
                 binwidth = 2,
                 aes(y=(-1)*..count.., fill = 'Total'))+
  geom_histogram(data=subset(graph,Sexo=="F" & Resultado.Pool == "Não Detectável"),
                 binwidth = 2,
                 aes(y=(-1)*..count.., fill = 'Não Detectáveis'))+
  scale_fill_manual(values = c('Total' = '#ffa58b','Não Detectáveis' = '#fe5246'))+
  labs(fill = 'Sexo Feminino:')+
  theme(legend.position = "top")
  
  
Graf_completo <- ggplot(data=graph,aes(x=Idade)) + 
  geom_histogram(data=subset(graph,Sexo=="M"),
                 binwidth = 2,
                 aes(y=..count.., fill = 'Amostra Masculina'))+
  geom_histogram(data=subset(graph,Sexo=="F"),
                 binwidth = 2,
                 aes(y=(-1)*..count.., fill = 'Amostra Feminina'))+
  geom_histogram(data=subset(graph,Sexo=="M" & Resultado.Pool == "Não Detectável"),
                 binwidth = 2,
                 aes(y=..count.., fill = 'Não Detectáveis masculinos'))+
  geom_histogram(data=subset(graph,Sexo=="F" & Resultado.Pool == "Não Detectável"),
                 binwidth = 2,
                 aes(y=(-1)*..count.., fill = 'Não Detectáveis femininos'))+
  coord_flip()+ 
  geom_hline(yintercept = 0)+
  theme_bw()+
  labs(y = 'Frequência', title = 'Pirâmide etária dos resultados dos Pools', fill = '')+
  scale_y_continuous(labels=abs(seq(-50,50,by = 20)), breaks=seq(-50,50,by = 20), limits = c(-55,55))+
  scale_fill_manual(values = c('Amostra Feminina' = '#ffa58b','Não Detectáveis femininos' = '#fe5246',
                               'Amostra Masculina' = '#8cbfff','Não Detectáveis masculinos' = '#466cff'))+
  theme(legend.position = "none")

plot_grid(
  Graf_completo
  , plot_grid(
    get_legend(legenda_fem)
    , get_legend(legenda_masc)
    , nrow = 1
  )
  , nrow = 2
  , rel_heights = c(8,1)
)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
graph <- base_completa %>% filter(Resultado.Pool != 'Não Detectável' |
                           is.na(Resultado.Pool != 'Não Detectável')) %>% 
    select(Resultado.Indiv.,Idade,Sexo) %>% 
  mutate(Idade = as.integer(Idade)) %>% 
  filter(!(is.na(Idade)),!(is.na(Resultado.Indiv.)),!(is.na(Sexo)))

legenda_masc <- ggplot(data=graph,aes(x=Idade)) + 
  geom_histogram(data=subset(graph,Sexo=="M"),
                 binwidth = 2,
                 aes(y=..count.., fill = 'Total'))+
  geom_histogram(data=subset(graph,Sexo=="M" & Resultado.Indiv. == "Detectável"),
               binwidth = 2,
               aes(y=..count.., fill = 'Detectáveis'))+
  scale_fill_manual(values = c('Total' = '#8cbfff','Detectáveis' = '#466cff'))+
  labs(fill = 'Sexo Masculino:')+
  theme(legend.position = "top")

legenda_fem <- ggplot(data=graph,aes(x=Idade)) + 
  geom_histogram(data=subset(graph,Sexo=="F"),
                 binwidth = 2,
                 aes(y=(-1)*..count.., fill = 'Total'))+
  geom_histogram(data=subset(graph,Sexo=="F" & Resultado.Indiv. == "Detectável"),
                 binwidth = 2,
                 aes(y=(-1)*..count.., fill = 'Detectáveis'))+
  scale_fill_manual(values = c('Total' = '#ffa58b','Detectáveis' = '#fe5246'))+
  labs(fill = 'Sexo Feminino:')+
  theme(legend.position = "top")
  
  
Graf_completo <- ggplot(data=graph,aes(x=Idade)) + 
  geom_histogram(data=subset(graph,Sexo=="M"),
                 binwidth = 2,
                 aes(y=..count.., fill = 'Amostra Masculina'))+
  geom_histogram(data=subset(graph,Sexo=="F"),
                 binwidth = 2,
                 aes(y=(-1)*..count.., fill = 'Amostra Feminina'))+
  geom_histogram(data=subset(graph,Sexo=="M" & Resultado.Indiv. == "Detectável"),
                 binwidth = 2,
                 aes(y=..count.., fill = 'Detectáveis masculinos'))+
  geom_histogram(data=subset(graph,Sexo=="F" & Resultado.Indiv. == "Detectável"),
                 binwidth = 2,
                 aes(y=(-1)*..count.., fill = 'Detectáveis femininos'))+
  coord_flip()+ 
  geom_hline(yintercept = 0)+
  theme_bw()+
  labs(y = 'Frequência', title = 'Pirâmide etária dos resultados Individuais', fill = '')+
  scale_y_continuous(labels=abs(seq(-30,30,by = 10)), breaks=seq(-30,30,by = 10), limits = c(-35,35))+
  scale_fill_manual(values = c('Amostra Feminina' = '#ffa58b','Detectáveis femininos' = '#fe5246',
                               'Amostra Masculina' = '#8cbfff','Detectáveis masculinos' = '#466cff'))+
  theme(legend.position = "none")

plot_grid(
  Graf_completo
  , plot_grid(
    get_legend(legenda_fem)
    , get_legend(legenda_masc)
    , nrow = 1
  )
  , nrow = 2
  , rel_heights = c(8,1)
)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
graph <- base_completa %>% mutate(Final = case_when(
  Resultado.Pool == 'Não Detectável' ~ 'Não Detectável',
  TRUE ~ Resultado.Indiv.)) %>% 
    select(Final,Idade,Sexo) %>% 
  mutate(Idade = as.integer(Idade)) %>% 
  filter(!(is.na(Idade)),!(is.na(Final)),!(is.na(Sexo)))

legenda_masc <- ggplot(data=graph,aes(x=Idade)) + 
  geom_histogram(data=subset(graph,Sexo=="M"),
                 binwidth = 2,
                 aes(y=..count.., fill = 'Total'))+
  geom_histogram(data=subset(graph,Sexo=="M" & Final == "Detectável"),
               binwidth = 2,
               aes(y=..count.., fill = 'Detectáveis'))+
  scale_fill_manual(values = c('Total' = '#8cbfff','Detectáveis' = '#466cff'))+
  labs(fill = 'Sexo Masculino:')+
  theme(legend.position = "top")

legenda_fem <- ggplot(data=graph,aes(x=Idade)) + 
  geom_histogram(data=subset(graph,Sexo=="F"),
                 binwidth = 2,
                 aes(y=(-1)*..count.., fill = 'Total'))+
  geom_histogram(data=subset(graph,Sexo=="F" & Final == "Detectável"),
                 binwidth = 2,
                 aes(y=(-1)*..count.., fill = 'Detectáveis'))+
  scale_fill_manual(values = c('Total' = '#ffa58b','Detectáveis' = '#fe5246'))+
  labs(fill = 'Sexo Feminino:')+
  theme(legend.position = "top")
  
  
Graf_completo <- ggplot(data=graph,aes(x=Idade)) + 
  geom_histogram(data=subset(graph,Sexo=="M"),
                 binwidth = 2,
                 aes(y=..count.., fill = 'Amostra Masculina'))+
  geom_histogram(data=subset(graph,Sexo=="F"),
                 binwidth = 2,
                 aes(y=(-1)*..count.., fill = 'Amostra Feminina'))+
  geom_histogram(data=subset(graph,Sexo=="M" & Final == "Detectável"),
                 binwidth = 2,
                 aes(y=..count.., fill = 'Detectáveis masculinos'))+
  geom_histogram(data=subset(graph,Sexo=="F" & Final == "Detectável"),
                 binwidth = 2,
                 aes(y=(-1)*..count.., fill = 'Detectáveis femininos'))+
  coord_flip()+ 
  geom_hline(yintercept = 0)+
  theme_bw()+
  labs(y = 'Frequência', title = 'Pirâmide etária dos resultados finais', fill = '')+
  scale_y_continuous(labels=abs(seq(-50,50,by = 20)), breaks=seq(-50,50,by = 20), limits = c(-55,55))+
  scale_fill_manual(values = c('Amostra Feminina' = '#ffa58b','Detectáveis femininos' = '#fe5246',
                               'Amostra Masculina' = '#8cbfff','Detectáveis masculinos' = '#466cff'))+
  theme(legend.position = "none")

plot_grid(
  Graf_completo
  , plot_grid(
    get_legend(legenda_fem)
    , get_legend(legenda_masc)
    , nrow = 1
  )
  , nrow = 2
  , rel_heights = c(8,1)
)
```